version: '3'
services:
  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    depends_on:
     - mongo
 
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/Muskan